### ISSUE TITLE
Crear archivo invencion del martillo electrico

### ISSUE THREAD

**Issue by yayu** [yayu/upso#5]
Describir el resultado de la wiki

**Comment by luanacisneros** [comment]
El martillo es una herramienta de percusión utilizada para golpear directa o indirectamente1 una pieza, causando su desplazamiento o deformación. El uso más común es para clavar (incrustar un clavo de acero en madera u otro material), calzar partes (por la acción de la fuerza aplicada en el golpe que la pieza recibe) o romper una pieza. Los martillos son a menudo diseñados para un propósito especial, por lo que sus diseños son muy variados. Un tipo de martillo, el martillo de carpintero, tiene una cuña abierta en la parte trasera para arrancar clavos.

Los primeros martillos datan de la Edad de Piedra del año 8000 a. C.;3 4 estos martillos constaban de una piedra atada a un mango con tiras de cuero. Más tarde, en el año 4000 a. C., con el descubrimiento del cobre,los egipcios comenzaron a fabricar la cabeza de los martillos en este material. Después, en el año 3500 a. C., durante la era de bronce se fabricaron con este material. Tiempo después aparecieron los martillos con orificios para el mango.

Martillo de orejas: su cabeza tiene dos funciones, la cara plana para clavar clavos, y la otra con ranura, para extraerlos.
Martillo de bola: de uso en mecánica.1 La bola sirve para concentrar los golpes en el forjado de una pieza cóncava o al deformar los bordes de un remache o roblón para realizar una unión por remachado.
Martillo de cuña: de uso en mecánica. La cuña sirve para el corte en caliente de piezas, de forma similar al uso de la tajadera para piezas mayores, o al cortafríos para espesores menores.
Mazos blandos: son martillos con caras de piel o plástico o goma que dañan menos que los metálicos y sólo se usan con ese fin, el dañar y marcar la chapa lo menos posible.
Martillo de peña: para trabajos ordinarios, de 300 a 350 g; el martillo de ebanista (peña) es un martillo de cuña de poco peso (100 g). Sirvió de mucho cuando en la época histórica.
